language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite RAILS_KEY=661d1ec03f0698a58dfd666666666666666666666666666666666666630a74cfef11867961ffffffffffffffffffffffff7c8710e1c DEVISE_SECRET_KEY=4d090a4936564aae62TTTTTTTTTTTTTTTTTTTTTTTTT14aa1f0c10f62ac4aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa7944fdb4b799e9bc471cee8983b
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
bundler_args: --binstubs=./bundler_stubs
deploy:
  provider: heroku
  api_key:
    secure: fg5jKUcIilcMPrgl8ljpVJiGTh2yNtURvhuQQ3WINqbwNXVyPdCfKThy0HEylBBVv8YpgeTH8dvfrr4l33TIGTXrfLwMNxUbRmB7HpkTeJxfOAiFZv7dYph0ptzEof2HvX2eBjZeHWXYzo/o0b5xwHxvWB6x+F+Z+3bzZ/h/NfE=
  app: gentle-dusk-2093
  on:
    rvm: 2.0.0
    repo: noj33/Portfolio_2
